Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-051f7e7f6c2f40dc1"
      KeyName: "Dev-keypair"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: "false"
          VolumeSize: 20
      - DeviceName: "/dev/sdk"
        NoDevice: {}
      Tags: 
      - Key: "name"
        Value: "jenkinsintegration"
      - Key: "Env"
        Value: "dev"